{{- if .Values.auth.krb5 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmaps.krb5Config }}
data:
  krb5.conf: |+
    [logging]
    {{- range $key, $value := .Values.auth.krb5.logging }}
    {{ $key }} = {{ $value }}
    {{- end }}
    
    [libdefaults]
    {{- range $key, $value := .Values.auth.krb5.libdefaults }}
    {{ $key }} = {{ $value }}
    {{- end }}
    
    [realms]
    {{- range $key, $value := .Values.auth.krb5.realms }}
    {{ $key }} = {
      kdc = {{ $value }}
    }
    {{- end }}
    
    [domain_realm]
    {{- range $name, $domain := .Values.auth.krb5.domain_realm }}
    {{ $name }} = {{ $domain }}
    {{- end }}
    {{ end }}

