apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmaps.slurmCgroupConf }}
data:
  cgroup.conf: |+
    ###
    # Slurm cgroup support configuration file.
    ###
    {{- range $key, $value := .Values.slurmctld.config.cgroups }}
    {{ $key }}={{ $value }}
    {{- end }}

