apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmaps.slurmGresConf }}
data:
  gres.conf: |+
    ###
    # Slurm GRES support configuration file.
    ###
    {{- range $key, $value := .Values.slurmctld.config.gres }}
    {{ $key }}={{ $value }}
    {{- end }}

