apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmaps.slurmEpilog }}
data:
  Z99UbiqFinish.sh: |+
    #!/bin/bash
    # Z99UbiqFinish.sh
    #
    # See the slurm man page re: Prolog for more information
    #

    # Make strings lower case for nice email formatting
