apiVersion: v1
kind: Secret
metadata:
  name: database-auth-secret
data:
  password: {{ .Values.dbPass | b64enc }}
  rootPassword: {{ .Values.dbPass | b64enc }}
  rootUser: {{ .Values.dbUser | b64enc }}
  rootHost: {{ .Values.dbHosts | b64enc }}
