{{- if .Values.auth.krb5 }}
apiVersion: v1
kind: Secret
metadata:
  name: sssd-creds
data:
  domain: {{ .Values.auth.krb5.creds.domain | b64enc }}
  username: {{ .Values.auth.krb5.creds.username | b64enc }}
  password: {{ .Values.auth.krb5.creds.password | b64enc }}
{{- end }}
