apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmd
  name: slurmd
spec:
  ports:
    - name: slurmd
      port: 6818
      targetPort: 6818
    - name: drain
      port: 22345
    - name: reconfigure
      port: 22346
    - name: queue-size
      port: 22347

  selector:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmd
  clusterIP: None
